config/routes.rb
Davinci::Application.routes.draw do

  scope "(:locale)", :locale => /en|es/ do
    namespace :management do
      resources :courses, :only => [:index, :new, :show]
      resources :users, :only => [:index, :new, :show]
      resource :school, :only => [:show]
    end

    resources :courses, :only => [:show] do
      get "file" => "courses#add_file"
      resources :grades, :only => [:index]
    end

    resources :users, only: [:show]

    resources :session, only: [:create]
    get 'login' => 'session#new', :as => :login
    get 'logout' => 'session#destroy', :as => :logout
  end

  get "uploads/:id/*name" => "gridfs#serve", :as => :serve

  get '/:locale' => 'home#index'
  root to: 'home#index'

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  
  layout 'session'
  
  helper :application

  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_to root_path(locale: current_user.language)
    else
      @message = view_context.alert_message(:error, "Login failed.")
      render :new
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/views/session/new.html.slim
== display_alert(@message)

= semantic_form_for '', url: session_index_path, html: {class: 'form-horizontal'} do |f|  
  = f.inputs t(:login) do
      = f.input :email, label: t(:email), as: :email, input_html: { autofocus: "autofocus" }
      = f.input :password, label: t(:password)
  = f.actions do
    = f.action :submit, disable_with: 'Logging in...', label: 'Log in'
    
- if Rails.env.development? or Rails.env.demo?
  p = t(:users_in_demo)
  ul.nav.nav-list.nav-tabs.nav-stacked
    .title 
      span = t(:user_owner)
      = link_to t(:login), session_index_path(email: 'owner@test.com', password: 'owner'), :method => :post
    li owner@test.com
    li owner
    .title 
      span = t(:user_admin)
      = link_to t(:login), session_index_path(email: 'admin@test.com', password: 'admin'), :method => :post
    li admin@test.com
    li admin
    
    .title
      span = t(:user_student)
      = link_to t(:login), session_index_path(email: 'student@test.com', password: 'student'), :method => :post
    li student@test.com
    li student
    
    .title
      span = t(:user_teacher)
      = link_to t(:login), session_index_path(email: 'teacher@test.com', password: 'teacher'), :method => :post
    li teacher@test.com
    li teacher