config/routes.rb
Davinci::Application.routes.draw do

  scope "(:locale)", :locale => /en|es/ do
    namespace :management do
      resources :courses, :only => [:index, :new, :show]
      resources :users, :only => [:index, :new, :show]
      resource :school, :only => [:show]
    end

    resources :courses, :only => [:show] do
      get "file" => "courses#add_file"
      resources :grades, :only => [:index]
    end

    resources :users, only: [:show]

    resources :session, only: [:create]
    get 'login' => 'session#new', :as => :login
    get 'logout' => 'session#destroy', :as => :logout
  end

  get "uploads/:id/*name" => "gridfs#serve", :as => :serve

  get '/:locale' => 'home#index'
  root to: 'home#index'

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title DaVinci LMS
    = stylesheet_link_tag    :application
    = javascript_include_tag :application
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    meta http-equiv="Content-Type" content="text/html;charset=UTF-8"
  body
    .navbar.navbar-default
      .container-fluid
        .navbar-header
          a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar

          = link_to 'DaVinci LMS', root_path, :class => 'brand'

          .nav-collapse
            ul.nav
              li class="divider-vertical"
              li
                = link_to root_path do
                  i class='icon-home'
                  span  = t(:home)
              li class="divider-vertical"
              li = link_to t(:courses), management_courses_path if current_user.admin? or current_user.owner?
              li = link_to t(:users), management_users_path if current_user.admin? or current_user.owner?
              li = link_to t(:school), management_school_path if current_user.owner?
            ul.nav.pull-right
              = render_widget :language
              li class="divider-vertical"
              li = link_to "#{current_user.name}", user_path(current_user.id)
              li = link_to :logout do
                i class='icon-off'
                span  = t(:logout)

    .container
      .row
        .span12
          .site-width
            .well data-pjax-container=true
              = yield

app/views/layouts/session.html.slim
doctype html
html
  head
    title DaVinci LMS
    = stylesheet_link_tag    :application
    = javascript_include_tag :application
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    meta http-equiv="Content-Type" content="text/html;charset=UTF-8"
  body
    .navbar.navbar-default role= 'navigation'
      .container-fluid
        .navbar-header
          a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar

          = link_to 'DaVinci LMS', root_path, :class => 'navbar-brand'

    .container
      .row
        .span12
          .site-width
            .well data-pjax-container=true
              = yield